server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://34.47.91.202:5432/
    username: postgres
    password: stroller
    driver-class-name: org.postgresql.Driver

logging:
  level:
    ROOT: info