server:
  port: 8090

spring:
  datasource:
    #    url: jdbc:h2:mem:testdb
    #    username: sa
    #    password:
    #    driver-class-name: org.h2.Driver
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: stroller
    driver-class-name: org.postgresql.Driver

logging:
  level:
    ROOT: info

slack:
  url: https://hooks.slack.com/services/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